---
image: docker:latest
services:
  - docker:dind

variables:
  DOCKER_DRIVER: overlay
  SPRING_PROFILES_ACTIVE: gitlab-ci

stages:
  - package
  - build
  - deploy

maven-war-compile:
  stage: package
  image: maven:3-jdk-8
  script: "mvn package -B"
  artifacts:
    paths:
      - target/*.war

docker-build:

  stage: build
  script:
    - docker build -t petclinic-app .
    - docker login myacrfitec.azurecr.io -u $ACR_USER -p $ACR_PASSWORD
    - docker tag petclinic-app myacrfitec.azurecr.io/petclinic-app:latest
    - docker push myacrfitec.azurecr.io/petclinic-app:latest 

deploy-azure:
  stage: deploy
  script:
    - az login --service-principal --username $APP_ID --password $PASSWORD --tenant $TENANT_ID
    - az aks get-credentials --resource-group=kubcluster --name=akcpetclinic

deploy-docker:
  stage: deploy
  script:
    - docker push petcliniccr.azurecr.io/petclinicfitec_petclinic-app:latest
