---
  version: '3.4'
  
  services:
    db:
      #restart: always
      image: mysql:5.7.8
      container_name: mysql-docker
      #ports: 
      #  - 3306:3306
      environment:
        MYSQL_DATABASE: petclinic
        MYSQL_ROOT_PASSWORD: root
        MYSQL_PASSWORD: petclinic
        MYSQL_USER: petclinic
#      healthcheck:
#       test: "/usr/bin/mysql --user=root --password=root--execute \"SHOW DATABASES;\""
#       interval: 2s
#       timeout: 20s
#       retries: 10"
    app:
      build: ./
      container_name: petclinicfitec_petclinic-app
      depends_on: 
        - db
      command: ["/usr/local/tomcat/wait-for-it.sh", "db:3306", "--timeout=300" ,"--", "catalina.sh", "run"]
      image: petclinicfitec_petclinic-app:latest
      environment:
        WAIT_HOSTS: mysql-docker:3306
        WAIT_HOSTS_TIMEOUT: 300
        WAIT_SLEEP_INTERVAL: 30
        WAIT_HOST_CONNECT_TIMEOUT: 30
      ports:
        - 8080:8080
  
